/*
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 * This file has been auto-generated by the confdc compiler.
 * Source: ncsc-out/modules/fxs/tailf-ned-cisco-ios-xr-meta.fxs
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 */

package com.tailf.packages.ned.iosxr.namespaces;

import com.tailf.conf.ConfNamespace;

/** Autogenerated namespace class for YANG module tailf-ned-cisco-ios-xr-meta.yang */
public class CiscoIosXrMeta extends ConfNamespace {
    public static final int hash = 726576819;
    public int hash() {
        return CiscoIosXrMeta.hash;
    }

    public static final String id = "http://tail-f.com/ned/cisco-iosxr/meta";
    public String id() {
        return CiscoIosXrMeta.id;
    }

    public static final String uri = "http://tail-f.com/ned/cisco-iosxr/meta";
    public String uri() {
        return CiscoIosXrMeta.uri;
    }

    public static final String prefix = "cisco-ios-xr-meta";
    public String prefix() {
        return CiscoIosXrMeta.prefix;
    }

    public CiscoIosXrMeta() {}

    public static int stringToHash(String str) {
        return ConfNamespace.stringToHash(str);
    }

    public static String hashToString(int hash) {
        return ConfNamespace.hashToString(hash);
    }

    public static final int    _number_of_retries = 1188193865;
    public static final String _number_of_retries_ = "number-of-retries";
    public static final int    _warning = 616981459;
    public static final String _warning_ = "warning";
    public static final int    _proxy_prompt = 1121728928;
    public static final String _proxy_prompt_ = "proxy-prompt";
    public static final int    _cisco_iosxr_auto_prompts = 1282364567;
    public static final String _cisco_iosxr_auto_prompts_ = "cisco-iosxr-auto-prompts";
    public static final int    _cisco_iosxr_connection_settings = 2111928610;
    public static final String _cisco_iosxr_connection_settings_ = "cisco-iosxr-connection-settings";
    public static final int    _version = 1714291735;
    public static final String _version_ = "version";
    public static final int    _cisco_iosxr_cached_show_enable = 1301445571;
    public static final String _cisco_iosxr_cached_show_enable_ = "cisco-iosxr-cached-show-enable";
    public static final int    _cisco_iosxr_show_running_strict_mode = 1980532298;
    public static final String _cisco_iosxr_show_running_strict_mode_ = "cisco-iosxr-show-running-strict-mode";
    public static final int    _answer = 638178487;
    public static final String _answer_ = "answer";
    public static final int    _remote_command = 1784444887;
    public static final String _remote_command_ = "remote-command";
    public static final int    _remote_address = 829475023;
    public static final String _remote_address_ = "remote-address";
    public static final int    _CSCtk60033_patch = 1802958932;
    public static final String _CSCtk60033_patch_ = "CSCtk60033-patch";
    public static final int    _cisco_iosxr_number_of_lines_to_send_in_chunk = 454871215;
    public static final String _cisco_iosxr_number_of_lines_to_send_in_chunk_ = "cisco-iosxr-number-of-lines-to-send-in-chunk";
    public static final int    _cisco_iosxr_log_verbose = 623052279;
    public static final String _cisco_iosxr_log_verbose_ = "cisco-iosxr-log-verbose";
    public static final int    _question = 1260341232;
    public static final String _question_ = "question";
    public static final int    _remote_port = 1738088052;
    public static final String _remote_port_ = "remote-port";
    public static final int    _cisco_iosxr_commit_method = 1626889660;
    public static final String _cisco_iosxr_commit_method_ = "cisco-iosxr-commit-method";
    public static final int    _remote_name = 734338841;
    public static final String _remote_name_ = "remote-name";
    public static final int    _cisco_iosxr_auto = 1389928299;
    public static final String _cisco_iosxr_auto_ = "cisco-iosxr-auto";
    public static final int    _cisco_iosxr_proxy_settings = 214104106;
    public static final String _cisco_iosxr_proxy_settings_ = "cisco-iosxr-proxy-settings";
    public static final int    _remote_password = 929903810;
    public static final String _remote_password_ = "remote-password";
    public static final int    _cisco_iosxr_config_method = 1449267317;
    public static final String _cisco_iosxr_config_method_ = "cisco-iosxr-config-method";
    public static final int    _vrf_forwarding_restore = 1295985965;
    public static final String _vrf_forwarding_restore_ = "vrf-forwarding-restore";
    public static final int    _id = 1279252765;
    public static final String _id_ = "id";
    public static final int    _remote_connection = 774750420;
    public static final String _remote_connection_ = "remote-connection";
    public static final int    _cisco_iosxr_config_warning = 2099727492;
    public static final String _cisco_iosxr_config_warning_ = "cisco-iosxr-config-warning";
    public static final int    _time_between_retry = 124382029;
    public static final String _time_between_retry_ = "time-between-retry";
    public static final int    _remote_prompt = 52371829;
    public static final String _remote_prompt_ = "remote-prompt";
    public static final int    _cisco_iosxr_transaction_id_method = 755244827;
    public static final String _cisco_iosxr_transaction_id_method_ = "cisco-iosxr-transaction-id-method";
}
