/*
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 * This file has been auto-generated by the confdc compiler.
 * Source: ncsc-out/modules/fxs/tailf-ned-cisco-ios-xr-oper.fxs
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 */

package com.tailf.packages.ned.iosxr.namespaces;

import com.tailf.conf.ConfNamespace;

/** Autogenerated namespace class for YANG module tailf-ned-cisco-ios-xr-oper.yang */
public class CiscoIosXrOper extends ConfNamespace {
    public static final int hash = 684415816;
    public int hash() {
        return CiscoIosXrOper.hash;
    }

    public static final String id = "http://tail-f.com/ned/cisco-iosxr/oper";
    public String id() {
        return CiscoIosXrOper.id;
    }

    public static final String uri = "http://tail-f.com/ned/cisco-iosxr/oper";
    public String uri() {
        return CiscoIosXrOper.uri;
    }

    public static final String prefix = "iosxr-op";
    public String prefix() {
        return CiscoIosXrOper.prefix;
    }

    public CiscoIosXrOper() {}

    public static int stringToHash(String str) {
        return ConfNamespace.stringToHash(str);
    }

    public static String hashToString(int hash) {
        return ConfNamespace.hashToString(hash);
    }

    public static final int    _path = 1002915403;
    public static final String _path_ = "path";
    public static final int    _cisco_iosxr_oper = 1576716391;
    public static final String _cisco_iosxr_oper_ = "cisco-iosxr-oper";
    public static final int    _secrets = 1439464346;
    public static final String _secrets_ = "secrets";
    public static final int    _cleartext = 140716928;
    public static final String _cleartext_ = "cleartext";
    public static final int    _regexp = 1858481280;
    public static final String _regexp_ = "regexp";
    public static final int    _encrypted = 1422131983;
    public static final String _encrypted_ = "encrypted";
}
