/*
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 * This file has been auto-generated by the confdc compiler.
 * Source: ../load-dir/csr-dashboard.fxs
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 */

package com.singtel.dashboard.namespaces;

import com.tailf.conf.ConfNamespace;

/** Autogenerated namespace class for YANG module csr-dashboard.yang */
public class csrDashboard extends ConfNamespace {
    public static final int hash = 2042390421;
    public int hash() {
        return csrDashboard.hash;
    }

    public static final String id = "http://com/singtel/nfv/csr/dashboard";
    public String id() {
        return csrDashboard.id;
    }

    public static final String uri = "http://com/singtel/nfv/csr/dashboard";
    public String uri() {
        return csrDashboard.uri;
    }

    public static final String prefix = "dbcsr";
    public String prefix() {
        return csrDashboard.prefix;
    }

    public csrDashboard() {}

    public static int stringToHash(String str) {
        return ConfNamespace.stringToHash(str);
    }

    public static String hashToString(int hash) {
        return ConfNamespace.hashToString(hash);
    }

    public static final int    _nickname = 718399243;
    public static final String _nickname_ = "nickname";
    public static final int    _sid = 1233827376;
    public static final String _sid_ = "sid";
    public static final int    _vcpe = 1299984498;
    public static final String _vcpe_ = "vcpe";
    public static final int    _network_service = 1286906704;
    public static final String _network_service_ = "network-service";
    public static final int    _service_name = 916440695;
    public static final String _service_name_ = "service-name";
}
