/*
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 * This file has been auto-generated by the confdc compiler.
 * Source: ../load-dir/nfv-types.fxs
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 */

package com.singtel.nfv.namespaces;

import com.tailf.conf.ConfNamespace;

/** Autogenerated namespace class for YANG module nfv-types.yang */
public class nfvTypes extends ConfNamespace {
    public static final int hash = 80406645;
    public int hash() {
        return nfvTypes.hash;
    }

    public static final String id = "http://com/singtel/nfv-types";
    public String id() {
        return nfvTypes.id;
    }

    public static final String uri = "http://com/singtel/nfv-types";
    public String uri() {
        return nfvTypes.uri;
    }

    public static final String prefix = "nfv-types";
    public String prefix() {
        return nfvTypes.prefix;
    }

    public nfvTypes() {}

    public static int stringToHash(String str) {
        return ConfNamespace.stringToHash(str);
    }

    public static String hashToString(int hash) {
        return ConfNamespace.hashToString(hash);
    }

    public static final int    _esp = 50;
    public static final String _esp_ = "esp";
    public static final int    _ingress = 0;
    public static final String _ingress_ = "ingress";
    public static final int    _cplus = 1;
    public static final String _cplus_ = "cplus";
    public static final int    _icmp = 1;
    public static final String _icmp_ = "icmp";
    public static final int    _none = 0;
    public static final String _none_ = "none";
    public static final int    _ipinip = 4;
    public static final String _ipinip_ = "ipinip";
    public static final int    _pim = 103;
    public static final String _pim_ = "pim";
    public static final int    _singnet = 2;
    public static final String _singnet_ = "singnet";
    public static final int    _complete_success = 0;
    public static final String _complete_success_ = "complete-success";
    public static final int    _ahp = 51;
    public static final String _ahp_ = "ahp";
    public static final int    _int_lan2 = 3;
    public static final String _int_lan2_ = "lan2";
    public static final int    _int_lan1 = 2;
    public static final String _int_lan1_ = "lan1";
    public static final int    _gre = 47;
    public static final String _gre_ = "gre";
    public static final int    _operational = 1;
    public static final String _operational_ = "operational";
    public static final int    _qos_lan2 = 2;
    public static final String _qos_lan2_ = "lan2";
    public static final int    _undeployed = 2;
    public static final String _undeployed_ = "undeployed";
    public static final int    _match_all = 0;
    public static final String _match_all_ = "match-all";
    public static final int    _in_progress = 0;
    public static final String _in_progress_ = "in-progress";
    public static final int    _enable = 1;
    public static final String _enable_ = "enable";
    public static final int    _any = 0;
    public static final String _any_ = "any";
    public static final int    _wan1 = 0;
    public static final String _wan1_ = "wan1";
    public static final int    _ip = 0;
    public static final String _ip_ = "ip";
    public static final int    _neq = 2;
    public static final String _neq_ = "neq";
    public static final int    _gt = 4;
    public static final String _gt_ = "gt";
    public static final int    _lan1 = 0;
    public static final String _lan1_ = "lan1";
    public static final int    _match_any = 1;
    public static final String _match_any_ = "match-any";
    public static final int    _permit = 1;
    public static final String _permit_ = "permit";
    public static final int    _megapop = 0;
    public static final String _megapop_ = "megapop";
    public static final int    _complete_failure = 1;
    public static final String _complete_failure_ = "complete-failure";
    public static final int    _non_operational = 2;
    public static final String _non_operational_ = "non-operational";
    public static final int    _qos_lan1 = 1;
    public static final String _qos_lan1_ = "lan1";
    public static final int    _eigrp = 88;
    public static final String _eigrp_ = "eigrp";
    public static final int    _egress = 1;
    public static final String _egress_ = "egress";
    public static final int    _nos = 94;
    public static final String _nos_ = "nos";
    public static final int    _ospf = 89;
    public static final String _ospf_ = "ospf";
    public static final int    _lt = 3;
    public static final String _lt_ = "lt";
    public static final int    _deny = 0;
    public static final String _deny_ = "deny";
    public static final int    _disable = 0;
    public static final String _disable_ = "disable";
    public static final int    _pcp = 108;
    public static final String _pcp_ = "pcp";
    public static final int    _eq = 1;
    public static final String _eq_ = "eq";
    public static final int    _udp = 17;
    public static final String _udp_ = "udp";
    public static final int    _wan2 = 1;
    public static final String _wan2_ = "wan2";
    public static final int    _lan2 = 1;
    public static final String _lan2_ = "lan2";
    public static final int    _range = 5;
    public static final String _range_ = "range";
    public static final int    _tcp = 6;
    public static final String _tcp_ = "tcp";
    public static final int    _igmp = 2;
    public static final String _igmp_ = "igmp";
}
