/*
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 * This file has been auto-generated by the confdc compiler.
 * Source: ../load-dir/vcpe-rpc.fxs
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 */

package com.singtel.nfv.namespaces;

import com.tailf.conf.ConfNamespace;

/** Autogenerated namespace class for YANG module vcpe-rpc.yang */
public class vcpeRpc extends ConfNamespace {
    public static final int hash = 620144299;
    public int hash() {
        return vcpeRpc.hash;
    }

    public static final String id = "http://com/singtel/vcpe";
    public String id() {
        return vcpeRpc.id;
    }

    public static final String uri = "http://com/singtel/vcpe";
    public String uri() {
        return vcpeRpc.uri;
    }

    public static final String prefix = "vcpe";
    public String prefix() {
        return vcpeRpc.prefix;
    }

    public vcpeRpc() {}

    public static int stringToHash(String str) {
        return ConfNamespace.stringToHash(str);
    }

    public static String hashToString(int hash) {
        return ConfNamespace.hashToString(hash);
    }

    public static final int    _as_number = 643256984;
    public static final String _as_number_ = "as-number";
    public static final int    _ban = 800159581;
    public static final String _ban_ = "ban";
    public static final int    _wan_cvlans = 1701010275;
    public static final String _wan_cvlans_ = "wan-cvlans";
    public static final int    _success_message = 34848571;
    public static final String _success_message_ = "success-message";
    public static final int    _nfv_vas_scheme = 609754520;
    public static final String _nfv_vas_scheme_ = "nfv-vas-scheme";
    public static final int    _pod = 1701062391;
    public static final String _pod_ = "pod";
    public static final int    _circuit_reference = 2002341947;
    public static final String _circuit_reference_ = "circuit-reference";
    public static final int    _routing_protocol = 667412728;
    public static final String _routing_protocol_ = "routing-protocol";
    public static final int    _management_ip = 1912824962;
    public static final String _management_ip_ = "management-ip";
    public static final int    _access_service_type = 1585299635;
    public static final String _access_service_type_ = "access-service-type";
    public static final int    _site_code = 1932980826;
    public static final String _site_code_ = "site-code";
    public static final int    _delete_vcpe = 747202152;
    public static final String _delete_vcpe_ = "delete-vcpe";
    public static final int    _lan_ip = 764389218;
    public static final String _lan_ip_ = "lan-ip";
    public static final int    _hostname = 840214230;
    public static final String _hostname_ = "hostname";
    public static final int    _sid = 1233827376;
    public static final String _sid_ = "sid";
    public static final int    _speed = 1423237997;
    public static final String _speed_ = "speed";
    public static final int    _wan_cvlan_id = 301122161;
    public static final String _wan_cvlan_id_ = "wan-cvlan-id";
    public static final int    _neighbor_passwd = 49227190;
    public static final String _neighbor_passwd_ = "neighbor-passwd";
    public static final int    _gateway = 501528536;
    public static final String _gateway_ = "gateway";
    public static final int    _create_vcpe = 972442935;
    public static final String _create_vcpe_ = "create-vcpe";
    public static final int    _wan_ip = 303987111;
    public static final String _wan_ip_ = "wan-ip";
    public static final int    _remote_as_number = 1183299412;
    public static final String _remote_as_number_ = "remote-as-number";
    public static final int    _egress_mac_address = 732618238;
    public static final String _egress_mac_address_ = "egress-mac-address";
    public static final int    _nfv_vas_reference = 807982623;
    public static final String _nfv_vas_reference_ = "nfv-vas-reference";
    public static final int    _brn = 1960721248;
    public static final String _brn_ = "brn";
    public static final int    _delete_vcpe_subinterface = 1759747294;
    public static final String _delete_vcpe_subinterface_ = "delete-vcpe-subinterface";
    public static final int    _dci_link_end_point = 215288694;
    public static final String _dci_link_end_point_ = "dci-link-end-point";
    public static final int    _lan_cvlans = 632369027;
    public static final String _lan_cvlans_ = "lan-cvlans";
    public static final int    _nfv_setup = 1777592390;
    public static final String _nfv_setup_ = "nfv-setup";
    public static final int    _result = 401396173;
    public static final String _result_ = "result";
    public static final int    _create_vcpe_subinterfaces = 629150995;
    public static final String _create_vcpe_subinterfaces_ = "create-vcpe-subinterfaces";
    public static final int    _errno = 1936954205;
    public static final String _errno_ = "errno";
    public static final int    _dci = 471570191;
    public static final String _dci_ = "dci";
    public static final int    _nfv_access_setup = 289750503;
    public static final String _nfv_access_setup_ = "nfv-access-setup";
    public static final int    _wan_cvlan_ip = 1949125355;
    public static final String _wan_cvlan_ip_ = "wan-cvlan-ip";
    public static final int    _egress_id = 352375484;
    public static final String _egress_id_ = "egress-id";
    public static final int    _product_code = 661551818;
    public static final String _product_code_ = "product-code";
    public static final int    _lan_cvlan_id = 1031958193;
    public static final String _lan_cvlan_id_ = "lan-cvlan-id";
    public static final int    _ingress_mac_address = 1723110412;
    public static final String _ingress_mac_address_ = "ingress-mac-address";
    public static final int    _modify_vcpe = 695689660;
    public static final String _modify_vcpe_ = "modify-vcpe";
    public static final int    _ingress_id = 1506047898;
    public static final String _ingress_id_ = "ingress-id";
    public static final int    _lan_cvlan_ip = 1098651265;
    public static final String _lan_cvlan_ip_ = "lan-cvlan-ip";
    public static final int    _brand = 528496938;
    public static final String _brand_ = "brand";
    public static final int    _service_name = 916440695;
    public static final String _service_name_ = "service-name";
    public static final String actionpoint_create_vcpe_subinterfaces = "create-vcpe-subinterfaces";
    public static final String actionpoint_delete_vcpe_subinterface = "delete-vcpe-subinterface";
    public static final String actionpoint_vcpe_create = "vcpe-create";
    public static final String actionpoint_vcpe_delete = "vcpe-delete";
    public static final String actionpoint_vcpe_modify = "vcpe-modify";
}
