/*
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 * This file has been auto-generated by the confdc compiler.
 * Source: ../load-dir/tailf-etsi-rel2-nfvo-esc-staged-delete.fxs
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 */

package com.tailf.nfvo.esc.namespaces;

import com.tailf.conf.ConfNamespace;

/** Autogenerated namespace class for YANG module tailf-etsi-rel2-nfvo-esc-staged-delete.yang */
public class tailfEtsiRel2NfvoEscStagedDelete extends ConfNamespace {
    public static final int hash = 1511263110;
    public int hash() {
        return tailfEtsiRel2NfvoEscStagedDelete.hash;
    }

    public static final String id = "http://tail-f.com/pkg/tailf-etsi-rel2-nfvo-esc-staged-delete";
    public String id() {
        return tailfEtsiRel2NfvoEscStagedDelete.id;
    }

    public static final String uri = "http://tail-f.com/pkg/tailf-etsi-rel2-nfvo-esc-staged-delete";
    public String uri() {
        return tailfEtsiRel2NfvoEscStagedDelete.uri;
    }

    public static final String prefix = "nfvo-rel2-esc-sd";
    public String prefix() {
        return tailfEtsiRel2NfvoEscStagedDelete.prefix;
    }

    public tailfEtsiRel2NfvoEscStagedDelete() {}

    public static int stringToHash(String str) {
        return ConfNamespace.stringToHash(str);
    }

    public static String hashToString(int hash) {
        return ConfNamespace.hashToString(hash);
    }

    public static final int    _esc = 1083533291;
    public static final String _esc_ = "esc";
    public static final int    _username = 870658415;
    public static final String _username_ = "username";
    public static final int    _delete = 593837355;
    public static final String _delete_ = "delete";
    public static final int    _deployment_name = 798518970;
    public static final String _deployment_name_ = "deployment-name";
    public static final int    _tenant = 967868883;
    public static final String _tenant_ = "tenant";
    public static final int    _deleted = 1406805957;
    public static final String _deleted_ = "deleted";
    public static final int    _staged_delete_esc = 1452002951;
    public static final String _staged_delete_esc_ = "staged-delete-esc";
}
