/*
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 * This file has been auto-generated by the confdc compiler.
 * Source: ../load-dir/utm-dashboard.fxs
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 */

package com.cisco.singtel.dashboardUtm.namespaces;

import com.tailf.conf.ConfNamespace;

/** Autogenerated namespace class for YANG module utm-dashboard.yang */
public class utmDashboard extends ConfNamespace {
    public static final int hash = 126591035;
    public int hash() {
        return utmDashboard.hash;
    }

    public static final String id = "http://com/singtel/nfv/utm/dashboard";
    public String id() {
        return utmDashboard.id;
    }

    public static final String uri = "http://com/singtel/nfv/utm/dashboard";
    public String uri() {
        return utmDashboard.uri;
    }

    public static final String prefix = "dbutm";
    public String prefix() {
        return utmDashboard.prefix;
    }

    public utmDashboard() {}

    public static int stringToHash(String str) {
        return ConfNamespace.stringToHash(str);
    }

    public static String hashToString(int hash) {
        return ConfNamespace.hashToString(hash);
    }

    public static final int    _deployment_type = 1665486832;
    public static final String _deployment_type_ = "deployment-type";
    public static final int    _hostname = 840214230;
    public static final String _hostname_ = "hostname";
    public static final int    _operational_status = 969376658;
    public static final String _operational_status_ = "operational-status";
    public static final int    _profile = 1538168517;
    public static final String _profile_ = "profile";
    public static final int    _local_vdom_id = 279698794;
    public static final String _local_vdom_id_ = "local-vdom-id";
    public static final int    _deployment_status = 1474863672;
    public static final String _deployment_status_ = "deployment-status";
    public static final int    _utm = 1554918511;
    public static final String _utm_ = "utm";
    public static final int    _service_type = 1145594576;
    public static final String _service_type_ = "service-type";
    public static final String callpoint_dashboard_utm_deployment_status = "dashboard-utm-deployment-status";
    public static final String callpoint_dashboard_utm_operational_status = "dashboard-utm-operational-status";
}
